user: openproject
group: openproject
targets:
  debian-8:
    <<: *debian
  ubuntu-14.04:
    <<: *debian
  sles-12:
    build_dependencies:
      - ImageMagick-devel
before_precompile: "packaging/setup"
crons:
  - packaging/cron/openproject-clear-old-sessions
services:
  - postgres
installer: https://github.com/pkgr/installer.git
wizards:
  - https://github.com/pkgr/addon-legacy-installer.git
  - https://github.com/pkgr/addon-mysql.git
  - https://github.com/oliverguenther/addon-apache2.git#feature/relative_root
  - https://github.com/finnlabs/addon-repositories.git#feature/relative_root
  - https://github.com/pkgr/addon-smtp.git
  - https://github.com/pkgr/addon-memcached.git
  - https://github.com/oliverguenther/addon-openproject.git#feature/relative_root
buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
