user: someuser
group: somegroup
targets:
  debian-7:
    build_dependencies:
      - libmagickwand-dev
      - libsqlite3-dev
    dependencies:
      - debconf
      - memcached
  fedora-20:
    build_dependencies:
      - ImageMagick-devel
    dependencies:
      - memcached
before_precompile: "packaging/setup"
after_install: "packaging/debian/postinst"
addons:
  - mysql
  - apache2
  - svn-dav
  - smtp
crons:
  - packaging/cron/openproject-clear-old-sessions
  - packaging/cron/openproject-create-svn-repositories
services:
  - postgres
