user: openproject
group: openproject
targets:
  ubuntu-20.04: &debian9
    build_dependencies:
      - libsqlite3-dev
    dependencies:
      - poppler-utils
      - unrtf
      - tesseract-ocr
      - catdoc
before_precompile: "packaging/setup"
after_precompile: "packaging/teardown"
installer: https://github.com/pkgr/installer.git
wizards:
  - https://github.com/pkgr/addon-legacy-installer.git
  - https://github.com/opf/addon-openproject-edition.git#bim
  - https://github.com/pkgr/addon-postgres
  - https://github.com/pkgr/addon-apache2.git
  - https://github.com/finnlabs/addon-repositories.git
  - https://github.com/pkgr/addon-smtp.git
  - https://github.com/pkgr/addon-memcached.git
  - https://github.com/opf/addon-openproject.git
buildpack: https://github.com/opf/heroku-buildpack-multi.git
